algoritmo exercicio 11
    real:n1,n2,soma,sub,divisao,resto
    início
        escreva("Digite o 1° número: ")
        leia(n1)
        escreva("Digite o 2° número: ")
        leia(n2)

        soma = n1 + n2
        sub = n1 - n2
        divisao = n1 / n2
        resto = n1 % n2

        escreva("A soma dos números é: "+soma)
        escreva("A subtração dos números é: "+sub)
        escreva("A divisão dos números é: "+divisao)
        escreva("O resto dos números é: "+resto)
    fim