algoritmo exercicio2
    literal: nome
    inteiro: quantidade
    literal: cargo
    início
        escreva("Digite o seu nome: ")
        leia(nome)
        escreva("Qual a quantidade de dependentes?: ")
        leia(quantidade)
        escreva("Digite o seu cargo na empresa: ")
        leia(cargo)

        escreva("Olá"+nome "A quantidade de dependentes é: "+quantidade "E o seu cargo é: "+cargo)
    fim